2025-05-12 12:03:19 [ERROR] src.errors.log.config: (sqlite3.OperationalError) no such table: diabetes
[SQL: select * from diabetes ;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: diabetes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\routes\diabetes_routes.py", line 56, in get_total
    http_response = request_adapter(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\adapters\request_adapter.py", line 8, in request_adapter
    http_response = controller(http_request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\presentations\controllers\diabetes\diabetes_dashboard_get_total.py", line 20, in handle
    response = self.__use_case.get_total(cnes, equipe)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\data\use_cases\diseases_dashboard\disease_dashboard.py", line 24, in get_total
    response = self.__repository.get_total(cnes, equipe)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\infra\db\repositories\disease\diseases_dashboard_local.py", line 127, in get_total
    cares = self._retrieve_cares(cnes, equipe)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\infra\db\repositories\disease\diseases_dashboard_local.py", line 124, in _retrieve_cares
    return pd.read_sql_query(sql, con=engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\pandas\io\sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\pandas\io\sql.py", line 1836, in read_query
    result = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\pandas\io\sql.py", line 1659, in execute
    return self.con.exec_driver_sql(sql, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1779, in exec_driver_sql
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: diabetes
[SQL: select * from diabetes ;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-12 12:03:19 [ERROR] src.errors.log.config: (sqlite3.OperationalError) no such table: hipertensao
[SQL: 
        with 
        lista as (
            select 
            distinct co_fat_cidadao_pec , d.co_dim_sexo,
            DATE(substr(co_dim_tempo_nascimento,1,4)||'-'||substr(co_dim_tempo_nascimento,5,2)||'-'||substr(co_dim_tempo_nascimento,7,2)) co_dim_tempo_nascimento
            from hipertensao d 
            where     
                d.co_dim_tempo_nascimento IS NOT NULL and d.co_dim_tempo_nascimento > 0
                
        ),
        idades as (
            select *, date(
                    date('now'),
                    '-'||(strftime('%m',co_dim_tempo_nascimento)-1)||' months',
                    '-'||(strftime('%d',co_dim_tempo_nascimento)-1)||' days'
                )-co_dim_tempo_nascimento AS idade  from lista 
        )
        select
            count(*) qdt , 
            CASE 
                when co_dim_sexo =1 then 'Masculino'
                when co_dim_sexo =2 then 'Feminino'
                when co_dim_sexo =3 then '-'
            END co_dim_sexo,
        CASE 
            when idade  >= 0 and idade <= 19 then '0 a 19 anos'
            when idade  >= 20 and idade <= 29 then '20 a 29 anos'
            when idade  >= 30 and idade <= 39 then '30 a 39 anos'
            when idade  >= 40 and idade <= 49 then '40 a 49 anos'
            when idade  >= 50 and idade <= 59 then '50 a 59 anos'
            when idade  >= 60  then '60+ anos'
        END faixa_etaria 
        from idades
        group by co_dim_sexo, faixa_etaria;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: hipertensao

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\routes\hypertension_routes.py", line 72, in get_age_group_gender
    http_response = request_adapter(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\adapters\request_adapter.py", line 8, in request_adapter
    http_response = controller(http_request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\presentations\controllers\hypertension\hypertension_get_age_group_gender.py", line 20, in handle
    response = self.__use_case.get_age_group_gender(cnes, equipe)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\data\use_cases\diseases_dashboard\disease_dashboard.py", line 34, in get_age_group_gender
    return self.__repository.get_age_group_gender(cnes, equipe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\infra\db\repositories\disease\diseases_dashboard_local.py", line 158, in get_age_group_gender
    pacientes = list(db_con.execute(sql))
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: hipertensao
[SQL: 
        with 
        lista as (
            select 
            distinct co_fat_cidadao_pec , d.co_dim_sexo,
            DATE(substr(co_dim_tempo_nascimento,1,4)||'-'||substr(co_dim_tempo_nascimento,5,2)||'-'||substr(co_dim_tempo_nascimento,7,2)) co_dim_tempo_nascimento
            from hipertensao d 
            where     
                d.co_dim_tempo_nascimento IS NOT NULL and d.co_dim_tempo_nascimento > 0
                
        ),
        idades as (
            select *, date(
                    date('now'),
                    '-'||(strftime('%m',co_dim_tempo_nascimento)-1)||' months',
                    '-'||(strftime('%d',co_dim_tempo_nascimento)-1)||' days'
                )-co_dim_tempo_nascimento AS idade  from lista 
        )
        select
            count(*) qdt , 
            CASE 
                when co_dim_sexo =1 then 'Masculino'
                when co_dim_sexo =2 then 'Feminino'
                when co_dim_sexo =3 then '-'
            END co_dim_sexo,
        CASE 
            when idade  >= 0 and idade <= 19 then '0 a 19 anos'
            when idade  >= 20 and idade <= 29 then '20 a 29 anos'
            when idade  >= 30 and idade <= 39 then '30 a 39 anos'
            when idade  >= 40 and idade <= 49 then '40 a 49 anos'
            when idade  >= 50 and idade <= 59 then '50 a 59 anos'
            when idade  >= 60  then '60+ anos'
        END faixa_etaria 
        from idades
        group by co_dim_sexo, faixa_etaria;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-12 12:03:19 [ERROR] src.errors.log.config: (sqlite3.OperationalError) no such table: diabetes
[SQL: select * from diabetes ;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: diabetes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\routes\diabetes_routes.py", line 56, in get_total
    http_response = request_adapter(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\adapters\request_adapter.py", line 8, in request_adapter
    http_response = controller(http_request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\presentations\controllers\diabetes\diabetes_dashboard_get_total.py", line 20, in handle
    response = self.__use_case.get_total(cnes, equipe)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\data\use_cases\diseases_dashboard\disease_dashboard.py", line 24, in get_total
    response = self.__repository.get_total(cnes, equipe)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\infra\db\repositories\disease\diseases_dashboard_local.py", line 127, in get_total
    cares = self._retrieve_cares(cnes, equipe)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\infra\db\repositories\disease\diseases_dashboard_local.py", line 124, in _retrieve_cares
    return pd.read_sql_query(sql, con=engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\pandas\io\sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\pandas\io\sql.py", line 1836, in read_query
    result = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\pandas\io\sql.py", line 1659, in execute
    return self.con.exec_driver_sql(sql, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1779, in exec_driver_sql
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: diabetes
[SQL: select * from diabetes ;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-12 12:03:19 [ERROR] src.errors.log.config: (sqlite3.OperationalError) no such table: hipertensao
[SQL: 
        with 
        lista as (
            select 
            distinct co_fat_cidadao_pec , d.co_dim_sexo,
            DATE(substr(co_dim_tempo_nascimento,1,4)||'-'||substr(co_dim_tempo_nascimento,5,2)||'-'||substr(co_dim_tempo_nascimento,7,2)) co_dim_tempo_nascimento
            from hipertensao d 
            where     
                d.co_dim_tempo_nascimento IS NOT NULL and d.co_dim_tempo_nascimento > 0
                
        ),
        idades as (
            select *, date(
                    date('now'),
                    '-'||(strftime('%m',co_dim_tempo_nascimento)-1)||' months',
                    '-'||(strftime('%d',co_dim_tempo_nascimento)-1)||' days'
                )-co_dim_tempo_nascimento AS idade  from lista 
        )
        select
            count(*) qdt , 
            CASE 
                when co_dim_sexo =1 then 'Masculino'
                when co_dim_sexo =2 then 'Feminino'
                when co_dim_sexo =3 then '-'
            END co_dim_sexo,
        CASE 
            when idade  >= 0 and idade <= 19 then '0 a 19 anos'
            when idade  >= 20 and idade <= 29 then '20 a 29 anos'
            when idade  >= 30 and idade <= 39 then '30 a 39 anos'
            when idade  >= 40 and idade <= 49 then '40 a 49 anos'
            when idade  >= 50 and idade <= 59 then '50 a 59 anos'
            when idade  >= 60  then '60+ anos'
        END faixa_etaria 
        from idades
        group by co_dim_sexo, faixa_etaria;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: hipertensao

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\routes\hypertension_routes.py", line 72, in get_age_group_gender
    http_response = request_adapter(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\main\adapters\request_adapter.py", line 8, in request_adapter
    http_response = controller(http_request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\presentations\controllers\hypertension\hypertension_get_age_group_gender.py", line 20, in handle
    response = self.__use_case.get_age_group_gender(cnes, equipe)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\data\use_cases\diseases_dashboard\disease_dashboard.py", line 34, in get_age_group_gender
    return self.__repository.get_age_group_gender(cnes, equipe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\src\infra\db\repositories\disease\diseases_dashboard_local.py", line 158, in get_age_group_gender
    pacientes = list(db_con.execute(sql))
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\ivantp\Downloads\flask-react-project\backend\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: hipertensao
[SQL: 
        with 
        lista as (
            select 
            distinct co_fat_cidadao_pec , d.co_dim_sexo,
            DATE(substr(co_dim_tempo_nascimento,1,4)||'-'||substr(co_dim_tempo_nascimento,5,2)||'-'||substr(co_dim_tempo_nascimento,7,2)) co_dim_tempo_nascimento
            from hipertensao d 
            where     
                d.co_dim_tempo_nascimento IS NOT NULL and d.co_dim_tempo_nascimento > 0
                
        ),
        idades as (
            select *, date(
                    date('now'),
                    '-'||(strftime('%m',co_dim_tempo_nascimento)-1)||' months',
                    '-'||(strftime('%d',co_dim_tempo_nascimento)-1)||' days'
                )-co_dim_tempo_nascimento AS idade  from lista 
        )
        select
            count(*) qdt , 
            CASE 
                when co_dim_sexo =1 then 'Masculino'
                when co_dim_sexo =2 then 'Feminino'
                when co_dim_sexo =3 then '-'
            END co_dim_sexo,
        CASE 
            when idade  >= 0 and idade <= 19 then '0 a 19 anos'
            when idade  >= 20 and idade <= 29 then '20 a 29 anos'
            when idade  >= 30 and idade <= 39 then '30 a 39 anos'
            when idade  >= 40 and idade <= 49 then '40 a 49 anos'
            when idade  >= 50 and idade <= 59 then '50 a 59 anos'
            when idade  >= 60  then '60+ anos'
        END faixa_etaria 
        from idades
        group by co_dim_sexo, faixa_etaria;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
